[2022-12-12 12:11:12,856] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_Paper.get_joke_task manual__2022-12-12T12:11:12.227226+00:00 [queued]>
[2022-12-12 12:11:12,865] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_Paper.get_joke_task manual__2022-12-12T12:11:12.227226+00:00 [queued]>
[2022-12-12 12:11:12,865] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:11:12,866] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 12:11:12,866] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:11:12,875] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_joke_task> on 2022-12-12 12:11:12.227226+00:00
[2022-12-12 12:11:12,878] {standard_task_runner.py:52} INFO - Started process 263 to run task
[2022-12-12 12:11:12,882] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_Paper', 'get_joke_task', 'manual__2022-12-12T12:11:12.227226+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpkzqib6_9', '--error-file', '/tmp/tmpkzdwwe5m']
[2022-12-12 12:11:12,884] {standard_task_runner.py:80} INFO - Job 8: Subtask get_joke_task
[2022-12-12 12:11:12,932] {task_command.py:369} INFO - Running <TaskInstance: daily_Paper.get_joke_task manual__2022-12-12T12:11:12.227226+00:00 [running]> on host cbcd6542cb8e
[2022-12-12 12:11:13,000] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_Paper
AIRFLOW_CTX_TASK_ID=get_joke_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T12:11:12.227226+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T12:11:12.227226+00:00
[2022-12-12 12:11:13,927] {logging_mixin.py:115} INFO - {'error': False, 'category': 'Pun', 'type': 'twopart', 'setup': 'Thank you student loans for getting me through college.', 'delivery': "I don't think I'll ever be able to repay you.", 'flags': {'nsfw': False, 'religious': False, 'political': False, 'racist': False, 'sexist': False, 'explicit': False}, 'id': 59, 'safe': True, 'lang': 'en'}
[2022-12-12 12:11:13,930] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning-paper.py", line 41, in get_joke
    return joke_dict['joke']
KeyError: 'joke'
[2022-12-12 12:11:13,956] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_Paper, task_id=get_joke_task, execution_date=20221212T121112, start_date=20221212T121112, end_date=20221212T121113
[2022-12-12 12:11:13,968] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task get_joke_task ('joke'; 263)
[2022-12-12 12:11:14,010] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 12:11:14,042] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
