[2022-12-12 17:54:30,612] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.get_joke_task manual__2022-12-12T17:54:29.414620+00:00 [queued]>
[2022-12-12 17:54:30,620] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.get_joke_task manual__2022-12-12T17:54:29.414620+00:00 [queued]>
[2022-12-12 17:54:30,620] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:54:30,621] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 17:54:30,621] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:54:30,633] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_joke_task> on 2022-12-12 17:54:29.414620+00:00
[2022-12-12 17:54:30,656] {standard_task_runner.py:52} INFO - Started process 1526 to run task
[2022-12-12 17:54:30,699] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'get_joke_task', 'manual__2022-12-12T17:54:29.414620+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpkabohpuj', '--error-file', '/tmp/tmpk7oygjqn']
[2022-12-12 17:54:30,740] {standard_task_runner.py:80} INFO - Job 303: Subtask get_joke_task
[2022-12-12 17:54:30,829] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.get_joke_task manual__2022-12-12T17:54:29.414620+00:00 [running]> on host 6bb81baa0a52
[2022-12-12 17:54:30,924] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=get_joke_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T17:54:29.414620+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T17:54:29.414620+00:00
[2022-12-12 17:54:31,726] {logging_mixin.py:115} INFO - {'error': False, 'category': 'Programming', 'type': 'single', 'joke': "I have a joke about Stack Overflow, but you would say it's a duplicate.", 'flags': {'nsfw': False, 'religious': False, 'political': False, 'racist': False, 'sexist': False, 'explicit': False}, 'safe': True, 'id': 301, 'lang': 'en'}
[2022-12-12 17:54:31,729] {python.py:173} INFO - Done. Returned value was: I have a joke about Stack Overflow, but you would say it's a duplicate.
[2022-12-12 17:54:31,784] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=daily_paper, task_id=get_joke_task, execution_date=20221212T175429, start_date=20221212T175430, end_date=20221212T175431
[2022-12-12 17:54:31,827] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 17:54:31,858] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
